version: '3.4'

services:
  frontend:
    ports:
      - "81:80"
    environment:
      STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"
  deltanotifier:
    volumes:
      - ./config/delta-producer:/config
  producer:
    image: redpencil/poc-diff-producer-service:latest
    links:
      - database
    volumes:
      - ./data/files:/share
      - ./config/producer:/config
    environment:
      PUBLICATION_GRAPH: "http://mu.semte.ch/application"
      DELTA_INTERVAL_MS: 512
  file:
    image: semtech/mu-file-service:latest
    links:
      - database
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/files:/share
  tunnel:
    image: redpencil/mu-tunnel:latest
    container_name: tunnel-producer
    volumes:
      - ./config/tunnel-producer:/config
    links:
      - producer
      - file
    external_links:
      - tunnel-consumer
    networks:
      - tunnel
      - default
    environment:
      TUNNEL_LOG_INBOUND: "true"
      TUNNEL_LOG_OUTBOUND: "true"

networks:
  tunnel:
    name: tunnel
