version: '3.4'

services:
  frontend:
    image: redpencil/frontend-poc-diff:latest
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"},{\"variables\":[],\"name\":\"clear\"}]"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    # TODO: When indexed deltas are merged, change this to an image
    build:
      context: git@github.com:ajuvercr/mu-authorization.git#feature/indexed_deltas
    volumes:
      - ./config/authorization:/config
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DELTA_CACHE_TIMEOUT: 50
    links:
      - triplestore:triplestore
    labels:
      - logging
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.19.0
    links:
      - database
    volumes:
      - ./config/resources:/config
  deltanotifier:
    image: semtech/mu-delta-notifier:latest
    environment:
      LOG_REQUESTS: "true"
      DEBUG_DELTA_SEND: "true"
      DEBUG_DELTA_MATCH: "true"
      DEBUG_TRIPLE_MATCHES_SPEC: "true"
    labels:
      - logging
