version: '3.9'

services:

  triplestore:
    image: tenforce/virtuoso:latest
    environment:
      - DBA_PASSWORD=access
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://mu.semte.ch/application

  deltanotifier:
    image: semtech/mu-delta-notifier:latest
    environment:
      LOG_REQUESTS: "true"
      DEBUG_DELTA_SEND: "true"
      DEBUG_DELTA_MATCH: "true"
      DEBUG_TRIPLE_MATCHES_SPEC: "true"
    labels:
      - logging

  database:
    image: semtech/mu-authorization:feature-consistency-with-credo
    volumes:
      - ./config/authorization:/config:Z
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DELTA_CACHE_TIMEOUT: 50
      INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
    links:
      - triplestore:triplestore
    labels:
      - logging

  file:
    image: semtech/mu-file-service:latest
    links:
      - database:database
    environment:
      LOG_LEVEL: "debug"
    volumes:
      - ./data/files:/share

  resource:
    image: semtech/mu-cl-resources:latest
    ports:
      - "85:80"
    links:
      - database:database
    volumes:
      - ./config/resources:/config:Z

  frontend:
    image: frontendapp
    volumes:
      - ./frontend-service/webapp/:/webapp/

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config:Z

  identifier:
    image: semtech/mu-identifier:feature-extended-timeout
    links:
      - dispatcher:dispatcher
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"},{\"variables\":[],\"name\":\"clear\"}]"

