version: '3.9'

services:

  triplestore:
    volumes:
      - ./data/db-consumer:/data:Z
    ports:
      - "8892:8890"

  deltanotifier:
    volumes:
      - ./config/delta-consumer:/config:Z

  consumer:
    image: producerconsumerapp
    links:
      - database:database
      - tunnel:tunnel
    volumes:
      - ./consumer-service/app:/app:Z
#      - ./config/consumer:/config:Z
    # These environment variables are default, but included here for illustration
    # The poc-diff-consumer-service README contains more information
    environment:
      NODE_ENV: "development"
      SYNC_BASE_URL: "http://identifier"
      TUNNEL_ENDPOINT: "http://tunnel/out"
      TUNNEL_DEST_IDENTITY: "producer@redpencil.io"

  frontend:
    ports:
      - "4202:4200"
    environment:
      STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"

  identifier:
    ports:
      - "82:80"

  tunnel:
    image: redpencil/mu-tunnel:latest
    container_name: tunnel-consumer
    volumes:
      - ./config/tunnel-consumer:/config:Z
    external_links:
      - tunnel-producer
    networks:
      - tunnel
      - default
    environment:
      TUNNEL_LOG_INBOUND: "true"
      TUNNEL_LOG_OUTBOUND: "true"

networks:
  tunnel:
    external: true
    name: tunnel

