version: '3.4'

services:
  frontend:
    ports:
      - "82:80"
  deltanotifier:
    volumes:
      - ./config/delta-consumer:/config
  consumer:
    image: redpencil/poc-diff-consumer-service:latest
    links:
      - db:database

