version: '3.9'

services:

  triplestore:
    volumes:
      - ./data/db:/data:Z
    ports:
      - "8891:8890"
  
  deltanotifier:
    volumes:
      - ./config/delta-producer:/config:Z
  
  syncfile:
    image: semtech/mu-file-service:latest
    links:
      - database
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/syncfiles:/share:Z

  producer:
    image: producerconsumerapp
    links:
      - database:database
    volumes:
      - ./producer-service/app:/app:Z
      - ./data/syncfiles:/share:Z
    environment:
      NODE_ENV: "development"
      PUBLICATION_GRAPH: "http://mu.semte.ch/application"
      DELTA_INTERVAL_MS: 512
  
  frontend:
    ports:
      - "4201:4200"
    environment:
      STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"

  identifier:
    ports:
      - "81:80"

  tunnel:
    image: redpencil/mu-tunnel:latest
    container_name: tunnel-producer
    volumes:
      - ./config/tunnel-producer:/config:Z
    links:
      - producer:producer
      - syncfile:syncfile
    external_links:
      - tunnel-consumer
    networks:
      - tunnel
      - default
    environment:
      TUNNEL_LOG_INBOUND: "true"
      TUNNEL_LOG_OUTBOUND: "true"

networks:
  tunnel:
    name: tunnel

