version: '3.4'

services:
  frontend:
    ports:
      - "82:80"
    environment:
      STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"
  deltanotifier:
    volumes:
      - ./config/delta-consumer:/config
  consumer:
    image: redpencil/poc-diff-consumer-service:latest
    volumes:
      - ./config/consumer:/config
    links:
      - database
      - tunnel
    # These environment variables are default, but included here for illustration
    # The poc-diff-consumer-service README contains more information
    environment:
      SYNC_BASE_URL: "http://identifier"
      TUNNEL_ENDPOINT: "http://tunnel/out"
      TUNNEL_DEST_IDENTITY: "producer@redpencil.io"
  triplestore:
    volumes:
      - ./data/db-consumer:/data
  tunnel:
    image: redpencil/mu-tunnel:latest
    container_name: tunnel-consumer
    volumes:
      - ./config/tunnel-consumer:/config
    external_links:
      - tunnel-producer
    networks:
      - tunnel
      - default
    environment:
      TUNNEL_LOG_INBOUND: "true"
      TUNNEL_LOG_OUTBOUND: "true"

networks:
  tunnel:
    external: true
    name: tunnel
