version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.8.1
    links:
      - dispatcher:dispatcher
    networks:
      - identifier
      - dispatcher
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"},{\"variables\":[],\"name\":\"clear\"}]"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
      - frontend:frontend
    networks:
      - dispatcher
      - frontend
      - resource
    volumes:
      - ./config/dispatcher:/config
  frontend:
    image: redpencil/frontend-poc-diff:latest
    links:
      - sink:backend
    networks:
      - frontend
      - sink
  sink:
    image: nginx
    networks:
      - sink
  db:
    image: semtech/mu-authorization:0.6.0-beta.1
    volumes:
      - ./config/authorization:/config
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
    links:
      - triplestore:triplestore
    labels:
      - logging
    networks:
      - db
      - deltanotifier
      - triplestore
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    networks:
      - triplestore
  resource:
    image: semtech/mu-cl-resources:1.19.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    networks:
      - resource
      - db
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    environment:
      LOG_REQUESTS: "true"
      DEBUG_DELTA_SEND: "true"
      DEBUG_DELTA_MATCH: "true"
      DEBUG_TRIPLE_MATCHES_SPEC: "true"
    labels:
      - logging
    networks:
      - deltanotifier
      - resource
networks:
  producer:
  file:
  identifier:
  dispatcher:
  frontend:
  sink:
  db:
  triplestore:
  resource:
  deltanotifier:
