version: '3.9'

services:
  frontend:
    ports:
      - "82:4200"
    environment:
      STATIC_FOLDERS_REGEX: "^/(assets|font|files)/"
  deltanotifier:
    volumes:
      - ./config/delta-consumer:/config:Z
  consumer:
    image: producerconsumerapp
    volumes:
      - ./config/consumer:/config:Z
      - ./consumer-service/app:/app:Z
    links:
      - database
      - tunnel
    # These environment variables are default, but included here for illustration
    # The poc-diff-consumer-service README contains more information
    environment:
      SYNC_BASE_URL: "http://identifier"
      TUNNEL_ENDPOINT: "http://tunnel/out"
      TUNNEL_DEST_IDENTITY: "producer@redpencil.io"
  triplestore:
    volumes:
      - ./data/db-consumer:/data:Z
  tunnel:
    image: redpencil/mu-tunnel:latest
    container_name: tunnel-consumer
    volumes:
      - ./config/tunnel-consumer:/config:Z
    external_links:
      - tunnel-producer
    networks:
      - tunnel
      - default
    environment:
      TUNNEL_LOG_INBOUND: "true"
      TUNNEL_LOG_OUTBOUND: "true"

networks:
  tunnel:
    external: true
    name: tunnel

